on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Jtreg Plugin Build
    runs-on: ubuntu-latest
    env:
      JAVA_OPTS: -Xmx4096m -XX:ReservedCodeCacheSize=512m

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: jetbrains
          java-version: 21

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew buildPlugin --no-daemon

      - name: Upload all plugin artifacts
        uses: actions/upload-artifact@v4
        with:
          name: plugins
          path: build/distributions/jtreg-plugin-*.zip
          if-no-files-found: error
          retention-days: 14